import type { RowData, TableColumn } from './types';

export const DEFAULT_SAMPLE_ROWS: RowData[] = [
  {
    id: 0,
    user: 'Chic Footitt',
    department: 'Operations',
    email: 'chic.footitt@yahoo.com',
    role: 'Viewer',
    enabled: true,
    employeeNumber: 1042,
    createdAt: '2023-01-16',
    lastLoginAt: '2025-03-18T09:45:00',
    teams: ['Workplace', 'Infrastructure'],
    website: 'https://chic.footitt.com',
    bioHtml: '<strong>Nulla sit amet nibh</strong> at augue facilisis viverra quis id dui.',
    notesMarkdown: '## Quick note\n- Prefers async updates\n- Uses the customer inbox\n\nSee [profile](https://example.com).',
    progress: 12,
    internalNotes: 'Hidden sample row note\nNeeds review before export.',
  },
  {
    id: 1,
    user: 'Kenton Worling',
    department: 'Support',
    email: 'kentonworling@icloud.com',
    role: 'Viewer',
    enabled: false,
    employeeNumber: 1043,
    createdAt: '2021-12-24',
    lastLoginAt: '2025-03-12T17:10:00',
    teams: ['Workplace'],
    website: 'https://kenton.worling.com',
    bioHtml: '<p>Duis viverra elementum ante, placerat sollicitudin ipsum laoreet nec.</p>',
    notesMarkdown: 'Supports the **string** and `markdown` renderers.',
    progress: 28,
    internalNotes: 'Hidden sample row note\nFollow up with support lead.',
  },
  {
    id: 2,
    user: 'Evelina Fender',
    department: 'Product',
    email: 'efender@outlook.com',
    role: 'Editor',
    enabled: true,
    employeeNumber: 1044,
    createdAt: '2022-01-03',
    lastLoginAt: '2025-03-20T11:05:00',
    teams: ['Product', 'Sales'],
    website: 'https://evelina.fender.com',
    bioHtml: '<ul><li>Donec in lorem</li><li>Sed eu mollis felis</li></ul>',
    notesMarkdown: '> Quote block for the markdown cell\n\n- First item\n- Second item',
    progress: 46,
    internalNotes: 'Hidden sample row note\nEscalated once this quarter.',
  },
  {
    id: 3,
    user: 'Lexis Speers',
    department: 'Design',
    email: 'lexisspeers@icloud.com',
    role: 'Admin',
    enabled: true,
    employeeNumber: 1045,
    createdAt: '2022-12-13',
    lastLoginAt: '2025-03-21T08:30:00',
    teams: ['Infrastructure', 'Design'],
    website: 'https://lexis.speers.com',
    bioHtml: '<a href="https://example.com">Linked note</a> with extra context.',
    notesMarkdown: '# Markdown title\n\nEmail support for `code` samples.',
    progress: 64,
    internalNotes: 'Hidden sample row note\nWaiting on design sign-off.',
  },
  {
    id: 4,
    user: 'Kenton Antonioni',
    department: 'People Ops',
    email: 'kenton.antonioni@icloud.com',
    role: 'Admin',
    enabled: true,
    employeeNumber: 1046,
    createdAt: '2022-04-15',
    lastLoginAt: '2025-03-19T14:22:00',
    teams: ['Success', 'Recruiting', 'Data'],
    website: 'https://kenton.antonioni.com',
    bioHtml: '<span style="font-style: italic;">Etiam bibendum auctor aliquet.</span>',
    notesMarkdown: 'Supports lists, links, and emphasis.',
    progress: 81,
    internalNotes: 'Hidden sample row note\nNeeds onboarding checklist refresh.',
  },
  {
    id: 5,
    user: 'Nanon Stit',
    department: 'Data',
    email: 'nanonstit@gmail.com',
    role: 'Editor',
    enabled: false,
    employeeNumber: 1047,
    createdAt: '2022-10-14',
    lastLoginAt: '2025-03-16T16:00:00',
    teams: ['Data'],
    website: 'https://nanon.stit.com',
    bioHtml: '<strong>Sed eu mollis felis.</strong> Nulla sit amet augue facilisis viverra.',
    notesMarkdown: 'Final row keeps the sample varied.',
    progress: 93,
    internalNotes: 'Hidden sample row note\nTemporarily disabled for audit.',
  },
  {
    id: 6,
    user: 'Mara Bellis',
    department: 'Finance',
    email: 'mara.bellis@proton.me',
    role: 'Viewer',
    enabled: true,
    employeeNumber: 1048,
    createdAt: '2021-08-09',
    lastLoginAt: '2025-03-17T07:20:00',
    teams: ['Finance', 'Data'],
    website: 'https://mara.bellis.example.com',
    bioHtml: '<p>Owns quarterly close coordination and variance reviews.</p>',
    notesMarkdown: 'Reviews budget deltas every Friday.',
    progress: 35,
    internalNotes: 'Quarter-end backup approver.\nPrefers email summaries.',
  },
  {
    id: 7,
    user: 'Pavel Dorsey',
    department: 'Security',
    email: 'pavel.dorsey@hey.com',
    role: 'Admin',
    enabled: true,
    employeeNumber: 1049,
    createdAt: '2020-11-02',
    lastLoginAt: '2025-03-22T06:55:00',
    teams: ['Infrastructure', 'Security'],
    website: 'https://pavel.dorsey.example.com',
    bioHtml: '<p><strong>Runs incident drills</strong> and access reviews.</p>',
    notesMarkdown: '- Owns SSO cleanup\n- Rotates secrets monthly',
    progress: 72,
    internalNotes: 'Security exception expires next month.\nCoordinate with IT.',
  },
  {
    id: 8,
    user: 'Iris Calder',
    department: 'Marketing',
    email: 'iris.calder@gmail.com',
    role: 'Editor',
    enabled: true,
    employeeNumber: 1050,
    createdAt: '2023-05-01',
    lastLoginAt: '2025-03-18T12:10:00',
    teams: ['Growth', 'Content'],
    website: 'https://iris.calder.example.com',
    bioHtml: '<p>Maintains lifecycle campaigns and homepage copy.</p>',
    notesMarkdown: 'Drafting the Q2 launch page with **brand** review pending.',
    progress: 57,
    internalNotes: 'Waiting on final hero artwork.\nCan self-serve most copy edits.',
  },
  {
    id: 9,
    user: 'Gideon Marsh',
    department: 'Operations',
    email: 'gideon.marsh@outlook.com',
    role: 'Viewer',
    enabled: false,
    employeeNumber: 1051,
    createdAt: '2021-06-18',
    lastLoginAt: '2025-03-11T19:40:00',
    teams: ['Logistics'],
    website: 'https://gideon.marsh.example.com',
    bioHtml: '<p>Coordinates vendor intake and warehouse exceptions.</p>',
    notesMarkdown: 'On leave this week. Route issues to the backup queue.',
    progress: 18,
    internalNotes: 'Account paused during leave.\nRe-enable after HR confirmation.',
  },
  {
    id: 10,
    user: 'Selah Rowe',
    department: 'Support',
    email: 'selah.rowe@icloud.com',
    role: 'Editor',
    enabled: true,
    employeeNumber: 1052,
    createdAt: '2024-02-26',
    lastLoginAt: '2025-03-22T10:12:00',
    teams: ['Support', 'Escalations'],
    website: 'https://selah.rowe.example.com',
    bioHtml: '<p>Focuses on VIP escalations and weekend coverage.</p>',
    notesMarkdown: 'Use the shared macro set and tag urgent tickets with `vip`.',
    progress: 67,
    internalNotes: 'Strong on escalations.\nNeeds additional billing training.',
  },
  {
    id: 11,
    user: 'Tobin Vale',
    department: 'Legal',
    email: 'tobin.vale@fastmail.com',
    role: 'Viewer',
    enabled: true,
    employeeNumber: 1053,
    createdAt: '2020-03-30',
    lastLoginAt: '2025-03-09T13:05:00',
    teams: ['Legal'],
    website: 'https://tobin.vale.example.com',
    bioHtml: '<p>Reviews procurement language and vendor redlines.</p>',
    notesMarkdown: 'Contract review SLA is currently **3 business days**.',
    progress: 41,
    internalNotes: 'Outside counsel review required for new templates.\nTrack in legal board.',
  },
  {
    id: 12,
    user: 'Rhea Solis',
    department: 'Product',
    email: 'rhea.solis@yahoo.com',
    role: 'Admin',
    enabled: true,
    employeeNumber: 1054,
    createdAt: '2019-09-12',
    lastLoginAt: '2025-03-21T15:48:00',
    teams: ['Product', 'Leadership'],
    website: 'https://rhea.solis.example.com',
    bioHtml: '<p>Leads roadmap planning and quarterly bet reviews.</p>',
    notesMarkdown: '# Roadmap\n\nFinalize the platform migration sequence.',
    progress: 88,
    internalNotes: 'Weekly product review host.\nKeep customer references current.',
  },
  {
    id: 13,
    user: 'Owen Pryce',
    department: 'Engineering',
    email: 'owen.pryce@proton.me',
    role: 'Editor',
    enabled: true,
    employeeNumber: 1055,
    createdAt: '2022-07-07',
    lastLoginAt: '2025-03-22T09:02:00',
    teams: ['Platform', 'Infrastructure'],
    website: 'https://owen.pryce.example.com',
    bioHtml: '<p>Owns deployment tooling and release observability.</p>',
    notesMarkdown: 'Document the rollback checklist before the next release.',
    progress: 76,
    internalNotes: 'Primary deploy contact.\nAvoid Friday schema changes.',
  },
  {
    id: 14,
    user: 'Juno Mercer',
    department: 'Sales',
    email: 'juno.mercer@gmail.com',
    role: 'Viewer',
    enabled: true,
    employeeNumber: 1056,
    createdAt: '2023-01-23',
    lastLoginAt: '2025-03-20T18:18:00',
    teams: ['Sales', 'West'],
    website: 'https://juno.mercer.example.com',
    bioHtml: '<p>Manages regional renewals and deal desk requests.</p>',
    notesMarkdown: 'Needs access to the latest pricing sheet.',
    progress: 52,
    internalNotes: 'Quarterly territory review pending.\nCoordinate with RevOps.',
  },
  {
    id: 15,
    user: 'Hale Winters',
    department: 'Success',
    email: 'hale.winters@outlook.com',
    role: 'Editor',
    enabled: false,
    employeeNumber: 1057,
    createdAt: '2021-04-06',
    lastLoginAt: '2025-03-08T08:42:00',
    teams: ['Success', 'Enterprise'],
    website: 'https://hale.winters.example.com',
    bioHtml: '<p>Handles enterprise onboarding and renewal prep.</p>',
    notesMarkdown: 'Reassign open accounts while access is disabled.',
    progress: 24,
    internalNotes: 'Coverage handoff in progress.\nRestore access after manager approval.',
  },
];

export const DEFAULT_SAMPLE_COLUMNS: TableColumn[] = [
  { sourceKey: 'user', label: 'User', format: 'avatar', editable: true, width: 260, description: 'Avatar-style name column.' },
  { sourceKey: 'department', label: 'Department', format: 'string', editable: true, width: 160, description: 'Plain text string column.' },
  { sourceKey: 'email', label: 'Email', format: 'email', editable: true, width: 260, description: 'Click-to-email address.', resizable: false },
  { sourceKey: 'role', label: 'Role', format: 'tag', editable: true, width: 120, description: 'Colored tag chip.' },
  { sourceKey: 'enabled', label: 'Enabled', format: 'boolean', editable: true, width: 100, align: 'center', description: 'Boolean toggle column.' },
  { sourceKey: 'employeeNumber', label: 'Employee #', format: 'number', editable: true, width: 120, align: 'right', description: 'Numeric editor column.' },
  { sourceKey: 'createdAt', label: 'Created at', format: 'date', editable: true, width: 140, description: 'Date picker column.' },
  { sourceKey: 'lastLoginAt', label: 'Last login', format: 'date time', editable: true, width: 180, description: 'Date and time editor column.' },
  { sourceKey: 'teams', label: 'Teams', format: 'multiple tags', editable: true, width: 260, description: 'Multi-tag chip column.' },
  { sourceKey: 'website', label: 'Website', format: 'link', editable: true, width: 240, description: 'External link column.' },
  { sourceKey: 'bioHtml', label: 'Bio HTML', format: 'html', editable: true, width: 320, description: 'Raw HTML rendering column.' },
  { sourceKey: 'notesMarkdown', label: 'Notes', format: 'markdown', editable: true, width: 320, description: 'Markdown rendering column.' },
  { sourceKey: 'progress', label: 'Progress', format: 'progress', editable: true, width: 180, align: 'center', description: '0-100 progress slider column.' },
  { sourceKey: 'internalNotes', label: 'Internal notes', format: 'multiline string', editable: true, hidden: true, resizable: false, description: 'Hidden multiline text sample column.' },
];

export const DEFAULT_COLUMN_ORDERING = DEFAULT_SAMPLE_COLUMNS.map((column) => column.sourceKey);
